<?php
// $Id: html5_tools_forms.module,v 1.7.2.1 2011/01/21 05:20:20 ericduran Exp $

/**
 * Implements hook_help().
 */
function html5_tools_forms_help($path, $arg) {
  switch ($path) {
    case 'admin/help#html5_tools_forms':
      $output = '';
      return $output;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function html5_tools_forms_form_system_site_information_settings_alter(&$form, &$form_state) {
  // Modify site configuration email textfield to a email field.
  if ($form['site_information']['site_mail']['#type'] == 'textfield') {
    $form['site_information']['site_mail']['#type'] = 'emailfield';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function html5_tools_forms_form_search_block_form_alter(&$form, &$form_state) {
  // Modify search block textfield to a searchfield.
  if ($form['search_block_form']['#type'] == 'textfield') {
    $form['search_block_form']['#type'] = 'searchfield';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function html5_tools_forms_form_search_form_alter(&$form, &$form_state) {
  // Modify search form to a search field.
  if ($form['basic']['keys']['#type'] == 'textfield') {
    $form['basic']['keys']['#type'] = 'searchfield';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function html5_tools_forms_form_user_register_form_alter(&$form, &$form_state) {
  // Modify the user registration field to use an email field.
  if ($form['account']['mail']['#type'] == 'textfield') {
    $form['account']['mail']['#type'] = 'emailfield';
  }
}